stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the app..."
    # Example: npm install && npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploying app to internal VM..."
    


    